# Start from Jenkins LTS base image for ARM architecture
FROM jenkins/jenkins:lts-jdk17

# Switch to root user to install dependencies
USER root

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    wget ca-certificates \
    && rm -rf /var/lib/apt/lists/*

############################################################
# 1) Install Java 21 (Temurin 21.0.5 for Linux ARM64)
############################################################
RUN wget -O /tmp/jdk-21.tar.gz \
    https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5+11/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.5_11.tar.gz \
 && mkdir /opt/jdk-21 \
 && tar -xzf /tmp/jdk-21.tar.gz -C /opt/jdk-21 --strip-components=1 \
 && rm /tmp/jdk-21.tar.gz

# Set JAVA_HOME to use Java 21
ENV JAVA_HOME=/opt/jdk-21
ENV PATH="$JAVA_HOME/bin:$PATH"

############################################################
# 2) Install Maven 3.9.9
############################################################
RUN wget -O /tmp/maven.tar.gz \
    https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz \
 && mkdir /opt/maven-3.9.9 \
 && tar -xzf /tmp/maven.tar.gz -C /opt/maven-3.9.9 --strip-components=1 \
 && rm /tmp/maven.tar.gz

ENV M2_HOME=/opt/maven-3.9.9
ENV PATH="$M2_HOME/bin:$PATH"

# Return to the Jenkins user (non-root)
USER jenkins

# Expose Jenkins default ports (web and agent)
EXPOSE 8080 50000
